#---------------------------------------
# Control-M/Agent docker container
# Edited by
#       Daniel Companeetz - BMC Software
# Contributions by
#       Aaron Baldwin - BMC Software
#       Gal Gafni Chen - BMC Software
#---------------------------------------

###Tested with the following OSes
# ensure you do a 
#   sudo docker pull rockylinux
#   sudo docker pull centos
FROM rockylinux:latest
#FROM centos:7

ARG AAPI_ENDPOINT
ARG AAPI_TOKEN
# AAPI_TOKEN is the Auth requirement for SaaS

### install basic packages
## Next line accelerates build by using deltarpm
# For Centos
#RUN  yum -y install deltarpm
#For Rocky (or Centos8)
RUN  yum -y install drpm
RUN  yum -y update 
RUN  yum -y install unzip \
	&& yum -y install sudo \
	&& yum -y install net-tools \ 
	&& yum -y install which \
	&& yum -y install wget \
	&& yum -y install psmisc

# ENABLE STRACE IF NEEDED FOR TROUBLESHOOTING SIGNALING
# connect to container and use strace -p 1 to see signals arriving to process
# RUN  yum -y install strace

# install nodejs
RUN  curl -k --silent --location https://rpm.nodesource.com/setup_16.x | bash - \
	&& yum -y install nodejs \
        && npm install -g npm@latest \
	&& node -v \
	&& npm -v 
 
# add controlm user and root to sudoers list
RUN  useradd -d /home/controlm -p controlm -m controlm \
	&& echo 'root ALL=(ALL) ALL' >> /etc/sudoers \
	&& echo 'controlm ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers 

# install java 11
RUN  sudo yum -y install java-11-openjdk \
        && java -version

# install ctm-automation-api kit
WORKDIR /root
RUN  mkdir /root/ctm-automation-api \
	&& cd /root/ctm-automation-api \
        # next line specific for saas
	&& curl --silent -k -O -H x-api-key:$AAPI_TOKEN https://$AAPI_ENDPOINT/automation-api/ctm-cli.tgz \  
	&& npm install -g ctm-cli.tgz \
        && rm ctm-cli.tgz \
	&& ctm -v 

# add controlm endpoint
USER controlm
WORKDIR /home/controlm

# next line specific for saas
RUN ctm env saas::add endpoint https://$AAPI_ENDPOINT/automation-api $AAPI_TOKEN \
	&& ctm env set endpoint 

# provision controlm agent image
RUN     cd \
	&& ctm provision image Agent_CentOS.Linux 

# Uncomment the images for the plugins needed
#RUN ctm provision image Application_Integrator_plugin.Linux 
#RUN ctm provision image Databases_plugin.Linux 
#RUN ctm provision image AWS_plugin.Linux 
#RUN ctm provision image Azure_plugin.Linux 
#RUN ctm provision image Hadoop_plugin.Linux 
#RUN ctm provision image Informatica_plugin.Linux 
#RUN ctm provision image MFT_plugin.Linux 

# Keep the following SAP lines together. Uncomment if needed.
#RUN ctm provision image SAP_plugin.Linux \
#COPY ./sapjco3.jar /home/controlm/ctm/cm/SAP/exe/sapjco
#RUN sudo chown controlm:controlm /home/controlm/ctm/cm/SAP/exe/sapjco/sapjco3.jar \
#        && sudo chmod 775 /home/controlm/ctm/cm/SAP/exe/sapjco/sapjco3.jar

# enable controlm agent utilities
RUN echo "source /home/controlm/.bash_profile" >> /home/controlm/.bashrc 

# Uninstall java 11. Remove comment to uninstall
# RUN sudo yum -y autoremove java-11-openjdk 

# Clean yum cache to reduce image size
RUN sudo yum clean all \
        && sudo rm -rf /var/cache/yum

################ Specific for Helix Control-M actions
# Add patches as needed. Below are for on-prem as example.
#COPY PAKAI.9.0.20.201_Linux-x86_64_INSTALL.BIN  /tmp
#COPY PAKAI.9.0.20.203_Linux-x86_64_INSTALL.BIN  /tmp

#RUN sudo chmod 755 /tmp/PAKAI.9.0.20.201_Linux-x86_64_INSTALL.BIN
#RUN source /home/controlm/.bashrc \
#         && /tmp/PAKAI.9.0.20.201_Linux-x86_64_INSTALL.BIN -s
#RUN sudo chmod 755 /tmp/PAKAI.9.0.20.203_Linux-x86_64_INSTALL.BIN
#RUN source /home/controlm/.bashrc \
#         && /tmp/PAKAI.9.0.20.203_Linux-x86_64_INSTALL.BIN -s

#RUN sudo rm -f /tmp/PAKAI*

# log4j vulnerability patch. This for both!
RUN sudo rm -f /home/controlm/ctm/toolbox/Usage_Measurement.jar

# Exposing Agent ports. Use range as not sure what will be used.
#    See run_register_controlm.sh to determine how that works
#EXPOSE 7000-8000

################ End of Specific for on-prem patches

### Keep these lines just before the end in case changes to the
###    run and decomm scripts are needed, to avoid re-build.
# copy run and register controlm agent script to container
COPY ./run_register_controlm.sh /home/controlm/
COPY ./deploy_test_jobs.json /home/controlm/
# give execute permissions to start/shut scripts
RUN  sudo chown controlm:controlm /home/controlm/*controlm.sh \
	&& sudo chmod 775 /home/controlm/*controlm.sh 

# CMD in exec mode (using []) is needed for signaling to work
# Signaling will ensure stopping the container deregister the agent
# use docker stop $container_id -t 60
# timeout is needed to ensure AAPI has time to process HG and agent removal
# docker stop default timeout is 10 sec and then a SIGKILL is sent.
CMD ["/home/controlm/run_register_controlm.sh"]

