#---------------------------------------
# Control-M/Agent docker container
# Edited by
#       Daniel Companeetz - BMC Software
# Contributions by
#       Brandi Coleman - BMC Software
#       Aaron Baldwin - BMC Software
#       Gal Gafni Chen - BMC Software
#---------------------------------------

# (c) 2020 - 2022 Daniel Companeetz, BMC Software, Inc.
# All rights reserved.

# BSD 3-Clause License

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.

# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# SPDX-License-Identifier: BSD-3-Clause
# For information on SDPX, https://spdx.org/licenses/BSD-3-Clause.html


###Tested with the following OSes
# ensure you do a
#   sudo docker pull rockylinux
#   sudo docker pull centos
FROM almalinux:latest
#FROM centos:7

# AAPI_ENDPOINT is the hostname part of the URL
ARG AAPI_ENDPOINT
# AAPI_TOKEN is the Auth requirement for SaaS
ARG AAPI_TOKEN
ARG AAPI_ENVIRONMENT="endpoint"
ENV aapi_env=$AAPI_ENVIRONMENT

# INSTALL_* is a flag to install the required plugin
ARG INSTALL_AIT=N
ARG INSTALL_MQL=N
ARG INSTALL_AMZ=N
ARG INSTALL_AZR=N
ARG INSTALL_CBD=N
ARG INSTALL_INF=N
ARG INSTALL_AFP=N
ARG INSTALL_RMC=N

# AAPI_TOKEN is the Auth requirement for SaaS

### install basic packages
## Next line to use deltarpm
# For Centos 7
#RUN  yum -y install deltarpm
#For Rocky (or Centos8)
RUN  yum -y install drpm

# Same for both OS
RUN  yum -y update
RUN  yum -y install unzip \
        && yum -y install sudo \
        && yum -y install net-tools \
        && yum -y install which \
        && yum -y install wget \
        && yum -y install psmisc

# ENABLE STRACE IF NEEDED FOR TROUBLESHOOTING SIGNALING
# connect to container and use strace -p 1 to see signals arriving to process
# RUN  yum -y install strace

# install nodejs
RUN  curl -k --silent --location https://rpm.nodesource.com/setup_16.x | bash - \
        && yum -y install nodejs \
        && npm install -g npm@latest \
        && node -v \
        && npm -v

# add controlm user and root to sudoers list
RUN  useradd -d /home/controlm -p controlm -m controlm \
        && echo 'root ALL=(ALL) ALL' >> /etc/sudoers \
        && echo 'controlm ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# install java 11
RUN  sudo yum -y install java-11-openjdk \
        && java -version

# install ctm-automation-api kit
WORKDIR /root
RUN  mkdir /root/ctm-automation-api \
        && cd /root/ctm-automation-api \
        # next line specific for saas
        && curl --silent -k -O -H x-api-key:$AAPI_TOKEN https://$AAPI_ENDPOINT/automation-api/ctm-cli.tgz \
        && npm install -g ctm-cli.tgz \
        && rm ctm-cli.tgz \
        && ctm -v

# add controlm endpoint
USER controlm
WORKDIR /home/controlm

# next line specific for saas
RUN ctm env saas::add $AAPI_ENVIRONMENT https://$AAPI_ENDPOINT/automation-api $AAPI_TOKEN \
        && ctm env set $AAPI_ENVIRONMENT

# provision controlm agent image
RUN     cd \
        && ctm provision image Agent_CentOS.Linux

# Uncomment the images for the plugins needed
RUN ctm env show
RUN ctm provision images Linux

# Install Plugin: Application Integrator
RUN if [ $INSTALL_AIT == "Y" ]; then \
       ctm provision image Application_Integrator_plugin.Linux; \
    else \
       echo "Do not install Application_Integrator_plugin.Linux"; \
    fi

# Install Plugin: Databases
RUN if [ $INSTALL_MQL == "Y" ]; then \
       ctm provision image Databases_plugin.Linux; \
    else \
       echo "Do not install Databases_plugin.Linux"; \
    fi

# Install Plugin: AWS
RUN if [ $INSTALL_AMZ == "Y" ]; then \
       ctm provision image AWS_plugin.Linux; \
    else \
       echo "Do not install AWS_plugin.Linux"; \
    fi

# Install Plugin: Azure
RUN if [ $INSTALL_AZR == "Y" ]; then \
       ctm provision image Azure_plugin.Linux; \
    else \
       echo "Do not install Azure_plugin.Linux"; \
    fi

# Install Plugin: Hadoop
RUN if [ $INSTALL_CBD == "Y" ]; then \
       ctm provision image Hadoop_plugin.Linux; \
    else \
       echo "Do not install Hadoop_plugin.Linux"; \
    fi

# Install Plugin: Application Integrator
RUN if [ $INSTALL_INF == "Y" ]; then \
       ctm provision image Informatica_plugin.Linux; \
    else \
       echo "Do not install Informatica_plugin.Linux"; \
    fi

# Install Plugin: Application Integrator
RUN if [ $INSTALL_AFP == "Y" ]; then \
       ctm provision image MFT_plugin.Linux; \
    else \
       echo "Do not install MFT_plugin.Linux"; \
    fi

# Keep the following SAP lines together. Uncomment if needed.
COPY ./sapjco3.jar /tmp/sapjco3.jar
RUN if [ $INSTALL_RMC == "Y" ]; then \
       ctm provision image SAP_plugin.Linux \
       && cp /tmp/sapjco3.jar /home/controlm/ctm/cm/SAP/exe/sapjco \
       && sudo chown controlm:controlm /home/controlm/ctm/cm/SAP/exe/sapjco/sapjco3.jar \
       && sudo chmod 775 /home/controlm/ctm/cm/SAP/exe/sapjco/sapjco3.jar \
    else \
       echo "Do not install SAP_plugin.Linux"; \
    fi

RUN sudo rm /tmp/sapjco3.jar

# enable controlm agent utilities
RUN echo "source /home/controlm/.bash_profile" >> /home/controlm/.bashrc

# Clean yum cache to reduce image size
RUN sudo yum clean all \
        && sudo rm -rf /var/cache/yum

################ Specific for Helix Control-M actions
# Add patches as needed. Below are for on-prem as example.
#COPY PAKAI.9.0.20.201_Linux-x86_64_INSTALL.BIN  /tmp
#COPY PAKAI.9.0.20.203_Linux-x86_64_INSTALL.BIN  /tmp

#RUN sudo chmod 755 /tmp/PAKAI.9.0.20.201_Linux-x86_64_INSTALL.BIN
#RUN source /home/controlm/.bashrc \
#         && /tmp/PAKAI.9.0.20.201_Linux-x86_64_INSTALL.BIN -s
#RUN sudo chmod 755 /tmp/PAKAI.9.0.20.203_Linux-x86_64_INSTALL.BIN
#RUN source /home/controlm/.bashrc \
#         && /tmp/PAKAI.9.0.20.203_Linux-x86_64_INSTALL.BIN -s

#RUN sudo rm -f /tmp/PAKAI*

# log4j vulnerability patch. This for both!
RUN sudo rm -f /home/controlm/ctm/toolbox/Usage_Measurement.jar

# Exposing Agent ports. Use range as not sure what will be used.
#    See run_register_controlm.sh to determine how that works
#EXPOSE 7000-8000

################ End of Specific for on-prem patches

### Keep these lines just before the end in case changes to the
###    run and decomm scripts are needed, to avoid re-build.
# copy run and register controlm agent script to container
COPY ./deploy_test_jobs.json /home/controlm/
COPY ./run_register_controlm.sh /home/controlm/
# give execute permissions to start/shut scripts
RUN  sudo chown controlm:controlm /home/controlm/*controlm.sh \
        && sudo chmod 775 /home/controlm/*controlm.sh

# CMD in exec mode (using [<json array>]) is needed for signaling to work, 
#    as it starts the script without a shell.
#    
# Signaling will ensure stopping the container deregister the agent
# use docker stop $container_id -t 60
# timeout is needed to ensure AAPI has time to process HG and agent removal
# docker stop default timeout is 10 sec and then a SIGKILL is sent.
CMD ["/home/controlm/run_register_controlm.sh", "$aapi_env", "$aapi_env"]
